Repository IGNF/pgrouting-procedures, pull requests merged in 2023-04, with the labels that each got.

#14 Remove duplicate
  docker/config/add_procedures.sh
  docker/config/create_dbuser.sh
  docker/config/pg_hba.conf
  docker/config/postgresql-setup
  docker/config/postgresql.conf
  docker/config/postgresql.sh
  documentation/developers/readme.md
  documentation/developers/sql_templates/readme.md
  readme.md
  scripts/add_procedures.sh
  sql/isochroneProcedures.sql
  sql/routeProcedures.sql
  sql/utilities.sql
Labels: enhancement

#15 fix(ci): update supported tag version to x.y.z
  .github/workflows/docker_publish.yml
Labels: bug, CI

#18 [ci] move the doc and docker part on master
  .github/workflows/docker_publish.yml
  .github/workflows/documentation.yml
Labels: CI

#19 [fix] update the doc ref to point on master branch
  changelog.md
  documentation/conf.py
  readme.md
Labels: documentation

#23 Update master to 2.1.2
  .github/workflows/documentation.yml
  changelog.md
  readme.md
Labels: bug, CI
